default_language_version:
    python: python3.8

repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black git_limiter tests
        language: python
        types: [python]

      - id: isort
        name: isort
        entry: poetry run isort git_limiter tests
        language: python
        types: [python]