default_language_version:
    python: python3.8

repos:
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.2.1
    hooks:
      - id: autoflake
        args: [
          "-r",
          "--in-place",
          "--remove-unused-variables",
          "--remove-all-unused-imports",
          "--ignore-init-module-imports"
        ]

  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3.8
        args: [
          "git_limiter",
          "tests",
        ]

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort
        args: [
          "isort",
          "git_limiter",
          "tests"
        ]