# CLI args/settings
DEFAULT_COMPARED_BRANCH = "main"
DEFAULT_MAX_INSERTIONS = 500
DEFAULT_MAX_DELETIONS = 200
DEFAULT_MAX_CHANGED_FILES = 15
DEFAULT_CONFIG = None


# CLI results
SUCCESS_CODE = 0
ERROR_CODE = 1
