site_name: git-limiter

docs_dir: src

theme:
  logo: assets/logo_simple.png
  name: material
  palette:
    - scheme: default
      primary: deep purple
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode


    # Palette toggle for dark mode
    - scheme: slate
      primary: deep purple
      toggle:
        icon: material/lightbulb
        name: Switch to light mode

  features:
    - content.code.annotate
    - content.tooltips
    - content.code.select
    - content.code.annotate
    - content.code.copy



markdown_extensions:
  # table support
  - tables
  # images
  - attr_list
  - md_in_html

repo_name: skonik/git-limiter
repo_url: https://github.com/skonik/git-limiter